### PR TITLE
Update api and urls

### PR DESCRIPTION
**Pull request by tkurki**
The goal of this PR is to gather the discussion for changes that should be done related to the apis and url leading towards Signal K 1.0.

NOT READY FOR MERGING

### CODE REVIEW

**Comment by tkurki** [comment]
A bit about the changes:
- left out protocols whose usage is not yet specified
- HTTP and WS preferably on the same port
- more specific paths return just the part of the tree from the specified point
- deemphasize https, as it is going to be troublesome on local boat
- move the version up the url
- remove addresses, replaced by root response
- remove authentication, needs separate document & discussion

**Comment by fabdrol** [comment]
@tkurki +1 for the changes, I have one comment. In an earlier discussion on the spec we talked about only using major versions; e.g. SK v1, v2, v3 and no minor and patch versions. There were various arguments for this, but the main one is simplicity for device and application makers. Having minor and patch versions could result in situations where to SK-enabled applications are compatible, but don't communicate because their developer didn't implement `semver` properly. 

I propose to move, unambiguously, to a version schema where:
- the latest stable version of the spec has a single version number (1, 2, 3)
- there is one development version at any given time. Changes that go into the next version of the spec end up here before we distill a stable version
- if required there will be a "experimental" version of the spec that can be used to test-drive ideas that are major and breaking (e.g. changes to conventions). 
- The `specification` repo will reflect this: `master` contains the current stable version, with tags for each previous stable version. The `development` branch contains the development version, if required there will be an `experimental` branch and of course there will be topic branches, patches etc to merge in to `development` or `experimental` when required.

Furthermore, shouldn't these documents be on the `specification` repo? I'd argue that these descriptions are fundamental parts of the specification, and having them in various locations causes confusion.

**Comment by tkurki** [comment]
Signal K spec = schemas + api specs. They should be versioned together, thus be in the same repo.

I suppose part of the web site content could come from the specification repo? @timmathews ?

**Comment by fabdrol** [comment]
@tkurki what's your view on my versioning comment?

**Comment by tkurki** [comment]
In effect you are saying that just use major version. Could work.

**Comment by sumps** [comment]
I think I am clear on all of the changes, but just to be sure, can you confirm my summary is correct;

For Version 1 Release, we are not going to include messaging services STOMP and MQTT and we are not going to recommend a secure HTTPS solution using SSL and the "Auth" API. These will be pushed back for consideration in Version 2.

After Bonjour/mDNS discovery, there is no need to read the Addresses rest API (which is removed), as the Http rest API will always be on Port 80 (why are we still saying 443 if HTTPS is outside of scope for V1?) along with the Websocket which is also on Port 80.

We are still saying that an alternate port might be used (between 49152 and 65535) but we are not saying how this is communicated and if the Addresses API is removed we need to explain how an alternate port is used.

We have changed the url format of Signal K, so that the Version field now covers the data format and APIs. Also no decimal place is included in the Version so only major version changes are supported in the Signal K url. This means that only changes that do not cause backward compatibility can be implemented without a Major Version change. 

For example it would be OK to add a new field that could only be read by new consumer apps or new server firmware, as long as it did not crash or cause problems for existing consumers and servers. If it did crash existing consumers and servers, it would have to wait until the next major release.

**Comment by timmathews** [comment]
@tkurki I could probably hack together some post-commit hooks to update the website whenever the documentation in the spec repo changes, but it won't happen before October. In the meantime, I think we ought to keep the documentation in the website repo since the site is the best place for end-users to consume the information. This also means removing anything from the specification wiki which is already on the website and getting anything on the wiki which isn't on the site into a condition to be published.

This also relates to signalk/specification#46. Ideally, the publication pipeline would look something like this:

```
            +----------------+
            | team agrees to |
            | spec change    |
            +----------------+
                   |
                   V
          +-------------------+
          | changes merged to |
          | master and tagged |
          | with new version  |
          +-------------------+
                   |
                   V
          +-------------------+
          | post commit hooks |
          | triggered         |
          +-------------------+
                /       \
               /         \
              /           \
             V             V
+----------------+  +--------------------+
| PDFs generated |  | markdown generated |
+----------------+  | with headers for   |
            |       | website            |
            |       +--------------------+
            |          |
            V          V
        +-------------------+
        | new page added to |
        | site with latest  |
        | version of spec   |
        | and download link |
        | for PDF version   |
        +-------------------+
                 |
                 V
        +-------------------+
        | announcement on   |
        | mailing list      |
        +-------------------+

```

**Comment by tkurki** [comment]
@sumps 

>For Version 1 Release, we are not going to include messaging services STOMP and MQTT and we are not going to recommend a secure HTTPS solution using SSL and the "Auth" API. These will be pushed back for consideration in Version 2.

Yes. SSL is perfectly usable for proper servers with certificates (like public servers on the Internet serving Signal K) but it is a pain to work with without certs, so it isn't something we should recommend for vessel local networks.

The authentication protocol is not well defined (like what happens after the auth request).

>After Bonjour/mDNS discovery, there is no need to read the Addresses rest API (which is removed), as the Http rest API will always be on Port 80 (why are we still saying 443 if HTTPS is outside of scope for V1?) along with the Websocket which is also on Port 80.

Not totally related to Bonjour. Address REST api would have helped in the case where you know the http port (can access the address api) but ws port is different from the http one. That use case is satisfied by the response from `/signalk`. 

Keep in mind that Bonjour works only in the local network. If I have Signal K HTTP api at https://foobar.signalk.org/signalk it can offer ws at wss://foobar2.signalk.org:64999/signalk/v1/stream - the ws address can be discovered starting with just the host name `foobar.signalk.org` and the inferred default `/signalk`path.

>We are still saying that an alternate port might be used (between 49152 and 65535) but we are not saying how this is communicated and if the Addresses API is removed we need to explain how an alternate port is used.

Address api would not help here as you need to know the address to access the api. Either local discovery via Bonjour, divination or manual entry.

>We have changed the url format of Signal K, so that the Version field now covers the data format and APIs. Also no decimal place is included in the Version so only major version changes are supported in the Signal K url. This means that only changes that do not cause backward compatibility can be implemented without a Major Version change.
>For example it would be OK to add a new field that could only be read by new consumer apps or new server firmware, as long as it did not crash or cause problems for existing consumers and servers. If it did crash existing consumers and servers, it would have to wait until the next major release.

Yes.

**Comment by tkurki** [comment]
@SignalK/contributors:  As we seem to be agreed on this I'm going to start making these changes in consumers & node server.

All JS consumers should move to using https://github.com/SignalK/signalk-js-client.

**Comment by tkurki** [comment]
I think we should keep this PR open to track the changes in the different components & merge once we have good coverage. If necessary we can add a link here to master.

**Comment by tkurki** [comment]
Node server changes done: https://github.com/SignalK/signalk-server-node/pull/46

**Comment by tkurki** [comment]
Correction to something I mentioned above: Bonjour has provisions for working outside the local network, but apparently it is far from hassle free.

**Comment by tkurki** [comment]
- [ ] endpoints: hostname is `undefined`

**Pull request merged**
